#!/bin/sh

module="scull"
device="scull"
mod="664"


# Invoke insmod
/sbin/insmod ./$module.ko $* || exit 1


# Remove stale node
rm  -rf /dev/${device}[0-3]

major=$(awk "\$2==\"$device\" {print \$1}" /proc/devices)

echo Major number is  $major 

mknod /dev/${device}0 c $major 0
